# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"G\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x1e\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\r.raft.Command\"1\n\x07\x43ommand\x12\n\n\x02op\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x9e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"/\n\rSubmitRequest\x12\x1e\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\r.raft.Command\"S\n\x0bSubmitReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\t\x12\x16\n\x0eleader_address\x18\x04 \x01(\t2\x96\x01\n\x0cRaftInternal\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply2>\n\nRaftClient\x12\x30\n\x06Submit\x12\x13.raft.SubmitRequest\x1a\x11.raft.SubmitReplyB\x13Z\x11raft-client/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021raft-client/proto'
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=91
  _globals['_COMMAND']._serialized_start=93
  _globals['_COMMAND']._serialized_end=142
  _globals['_REQUESTVOTEREQUEST']._serialized_start=144
  _globals['_REQUESTVOTEREQUEST']._serialized_end=247
  _globals['_REQUESTVOTEREPLY']._serialized_start=249
  _globals['_REQUESTVOTEREPLY']._serialized_end=303
  _globals['_APPENDENTRIESREQUEST']._serialized_start=306
  _globals['_APPENDENTRIESREQUEST']._serialized_end=464
  _globals['_APPENDENTRIESREPLY']._serialized_start=466
  _globals['_APPENDENTRIESREPLY']._serialized_end=517
  _globals['_SUBMITREQUEST']._serialized_start=519
  _globals['_SUBMITREQUEST']._serialized_end=566
  _globals['_SUBMITREPLY']._serialized_start=568
  _globals['_SUBMITREPLY']._serialized_end=651
  _globals['_RAFTINTERNAL']._serialized_start=654
  _globals['_RAFTINTERNAL']._serialized_end=804
  _globals['_RAFTCLIENT']._serialized_start=806
  _globals['_RAFTCLIENT']._serialized_end=868
# @@protoc_insertion_point(module_scope)
